name: tex_markdown
description: This package is used to create flutter widget that can render markdown and latex formulas. It is very simple to use and uses native flutter components.
version: 0.1.9
homepage: https://github.com/saminsohag/flutter_packages/tree/main/tex_markdown
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # tex_text: ^0.1.8
  tex_text:
    path: ../tex_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: